### ISSUE TITLE
About estimated camera poses on Synthetic Sequences.

### ISSUE THREAD

**Issue by junshengzhou** [JingwenWang95/go-surf#10]
Hi,
Thanks for sharing you great work! 
I found that go-surf performs well in estimating the camera poses, so I wonder if you can share the estimated camera poses on 10 synthetic scenes (reported in Table. 2). I would like to use the estimated camera poses of go-surf as an initialization. Thanks for your time!

**Comment by JingwenWang95** [comment]
Hi @junshengzhou! Unfortunately I don't have access to the exact checkpoints I used to make Table 2 as I have cleaned my hard drive since after the submission. Can you run the code yourself? It will save the poses in the checkpoints. The result should be similar and it won't take too long (maybe 5 to 6 hours for a single 2080ti) to get all the results.

**Comment by junshengzhou** [comment]
OK! I will run the code to get the poses, thanks for your quick reply!
