### ISSUE TITLE
Question about the grid dimension

### ISSUE THREAD

**Issue by Liuyveg** [JingwenWang95/go-surf#3]
Thanks for your great work. 
https://github.com/JingwenWang95/go-surf/blob/3a361478c3c9506daab14d5ab6c6e7e352b90a0f/model/utils.py#L74
why the computed grid dim should be added 1?

**Comment by JingwenWang95** [comment]
Hi @Liuyveg, we did this because we followed `align_corners=True` when we defined our volume, which means the features are stored at the corners of the voxels. That's why in each dimension our `voxel_dim` is always `num_of_grids + 1`. For the same reason, when we upsample the volume we have to do something like `new_voxel_dim = (old_voxel_dim - 1) * up_factor + 1`. And this is exactly what line 74 is doing.
