### ISSUE TITLE
Neural RGBD Baseline

### ISSUE THREAD

**Issue by XuqianRen** [JingwenWang95/go-surf#6]
Hi, thank you for your excellent project, I noticed that the result of the Neural RGBD baseline and some other baselines you reported in your paper are better than the result in the original Neural RGBD paper. I want to ask what other settings you have changed to get the current baseline results, except the samples you chose for each ray.  What is the most effective change to achieve the current better results?

**Comment by JingwenWang95** [comment]
Hi @XuqianRen! So the reason the numbers are inconsistent is because we changed the culling strategy before running the evaluation. More specifically, we remove the mesh vertice if 1. it's not inside any camera frustum (not observed) 2. it's occluded by other geometry (occluded) 3. it doesn't enough valid depth measurement (such as missing depth area in the window). NeuralRGBD only applied criteria 1 and 2, and 3 is a new criteria we introduced. We also fixed a bug in depth rendering in their original culling script (which affected criteria 2). We applied our new culling strategy to all the reconstructed meshes and gt meshes, and that's why the numbers in our tables are not consistent.

For more details, you can refer to our [culling script](https://github.com/JingwenWang95/go-surf/blob/c82e976cd971fcdcdfe8af40e373acab795c831b/tools/frustum_culling.py) or our supplementary material. You can refer to [eval_mesh.py ](https://github.com/JingwenWang95/go-surf/blob/c82e976cd971fcdcdfe8af40e373acab795c831b/eval_mesh.py) for the whole evaluation pipeline.

**Comment by XuqianRen** [comment]
Thank you for your quick reply @JingwenWang95, so you only change the evaluation script, and the training parameters remain the same with the original repositories?

**Comment by JingwenWang95** [comment]
Yeah, only culling strategy is changed. Everything else is the same.

**Comment by XuqianRen** [comment]
Thank you again for your reply.

**Comment by XuqianRen** [comment]
Hi @JingwenWang95, I have tried to use your cull script to cull the mesh generated by the original neural_rgb project, this is the process I deal with the generated mesh:
first I extract the optimized pose use their extract_optimized_poses.py
then I get the transform matrix of transforming the optimized_pose to ground truth pose, then apply it to transform the mesh
finally I use your cull script and get the evaluation result.

But I found only the breakfast_room scene's evaluation result is similar to the result you wrote in your paper: {"Acc": 0.014506831033098983, "Comp": 0.014966911023022363, "C-L1": 0.014736871028060674, "NC": 0.964751580718765, "F-score": 0.9894044838834599}.

And other's is worse, such as the complete_kitchen: {"Acc": 0.022827639423042206, "Comp": 0.8365577646766191, "C-L1": 0.4296927020498307, "NC": 0.832096750472259, "F-score": 0.6056972965026465} (I visualize the culled mesh of this scene, I found some region of this reconstructed scene have culled, it seems that the scene bound that used to cull the mesh isn't correct.)

the icl_living_room: {"Acc": 0.009187239170744356, "Comp": 0.08402908937603093, "C-L1": 0.04660816427338764, "NC": 0.9077545536288937, "F-score": 0.900606739574223}

I think maybe there are some problems with my way to use your evaluation script, but I don't know what's the problem, could you give me more advice?
