### ISSUE TITLE
How to get the gt_mesh_culled?

### ISSUE THREAD

**Issue by Liuyveg** [JingwenWang95/go-surf#7]
Hi, how did you get the `gt_mesh_culled`? 

https://github.com/JingwenWang95/go-surf/blob/c82e976cd971fcdcdfe8af40e373acab795c831b/tools/frustum_culling.py#L15
Was it obtained by using this function? And how to set the function parameters？

https://github.com/JingwenWang95/go-surf/blob/c82e976cd971fcdcdfe8af40e373acab795c831b/eval_mesh.py#L54
When I use this function to get the `gt_mesh_culled` of scene mesh and the parameter `max_edge` also set 0.015, sometimes the process would be killed.

I wonder how to obtain the same result as you.

**Comment by JingwenWang95** [comment]
Hi @Liuyveg! Yes, that is the function you can use to get culled gt mesh. The reason your process got killed is because of the [subdivide step](https://github.com/JingwenWang95/go-surf/blob/master/tools/frustum_culling.py#L22), which will recursively subdivide the original mesh such that all its faces will have edge length smaller than `max_edge`. This step can sometimes consume very large CPU RAM especially for gt meshes. We use 1.5cm for subdividng the reconstructed mesh (which follows the protocal in NeuralRGBD), but for gt mesh you might try setting it to a larger number such as 5cm because the gt mesh cotains some very large faces, for example a large wall in gt mesh might be represented with two very large triangles.

**Comment by Liuyveg** [comment]
OK, I see. Thank you!
